### PR TITLE
removed all log.Fatal statements, replaced them with log.Println statements

### LINKED ISSUE #1: checkErr() Function Renders Unusable in Server Contexts
It's not currently possible to use this library in a server, because it's impossible to catch and recover from errors.

### PR DESCRIPTION
**Pull request by pnovotnak**
Should make error handling much easier for implementers, closes #1

### CODE REVIEW

**Comment by kdvh** [comment]
Thanks @pnovotnak. I agree that this change would make error handling easier for a client. However, I think checkResponseStatus() will also need to be amended to return (rather than log) errors:

```
func checkResponseStatus(status, errorStr string) error {
    if status != "success" {
        if errorStr != "" {
            return ErrRequestFailedReason(errorStr)
        }
        return ErrRequestFailed
    }
    return nil
}
```

And the call would be something like:

```
    url, err := buildURL(s.BaseURL, "ajax.php", query)
    if err != nil {
        return &AccountResponse{}, err
    }
    err = s.GetJSON(url, &account)
    if err != nil {
        return &AccountResponse{}, err
    }
    err = checkResponseStatus(account.Status, account.Error)
    if err != nil {
        return &AccountResponse{}, err
    }
    return account.Response, nil
```

**Comment by pnovotnak** [comment]
Oh yeah, I think you are right!

I'll make that change after work tomorrow.

**Comment by kdvh** [comment]
See latest [commit](https://github.com/kdvh/whatapi/commit/30b9c2d2cb31697848b1541dbdad9c0b25a04754).

**Comment by pnovotnak** [comment]
Noice! Sorry, work + school caught up with me

**Pull request closed without merging**
